package com.ticketpulse.domain.model

data class Event(
    val id: String,
    val title: String,
    val slug: String,
    val category: String,
    val status: String,
    val venue: String,
    val city: String,
    val country: String?,
    val startsAt: String,
    val endsAt: String?,
    val coverImage: String?,
    val featured: Boolean = false,
    val organizerName: String?,
    val organizerImage: String?,
    val lowestPrice: Double? = null,
    val currency: String? = "USD",
    val description: String? = null,
    val address: String? = null,
    val googleMapsUrl: String? = null,
    val tags: List<String> = emptyList(),
    val promoImages: List<String> = emptyList(),
    val faq: String? = null,
    val tiers: List<TicketTier> = emptyList(),
)

data class TicketTier(
    val id: String,
    val name: String,
    val description: String?,
    val price: Double,
    val currency: String,
    val totalQuantity: Int,
    val soldQuantity: Int?,
    val remaining: Int,
    val maxPerOrder: Int = 10,
    val earlyBirdPrice: Double? = null,
    val earlyBirdUntil: String? = null,
    val groupPrice: Double? = null,
    val groupMinQty: Int? = null,
    val salesStart: String? = null,
    val salesEnd: String? = null,
)
